apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: riyan
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: vprodb
        image: riyanuddin/db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: vprodbpass   
        - name: MYSQL_DATABASE
          value: accounts 
