apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: riyan
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: vproweb
        image: riyanuddin/web
        ports:
        - containerPort: 80
