apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: riyan
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: vproapp
        image: riyanuddin/app
        ports:
        - containerPort: 8080
